import type { Project } from '@/lib/types';

export const projectsFr: Project[] = [
  {
    slug: "file-sharing-system",
    doorNumber: "01",
    order: 1,
    complexity: 2,
    category: "software",
    doorKind: "blueprint",
    title: "File Sharing System",
    type: "Projet d'analyse logicielle et de conception de système",
    tagline: `Analyse et conception d'un système de partage de fichiers avant l'implémentation. Aucun code, et c'était le but : le livrable était une spécification assez précise pour servir de base à la construction.`,
    preview: `Analyse orientée cas d'utilisation d'un système de partage de fichiers multiutilisateur, des diagrammes d'acteurs jusqu'à une spécification écrite qu'une équipe pouvait implémenter.`,
    previewStack: "UML · Specification · Design",
    status: "Delivered",
    links: [],
    meta: [["Rôle", "Analyse et conception"], ["Méthode", "Cas d'utilisation UML"], ["Année", "2026"], ["Statut", "Livré"]],
    whyRated: `Modélisation et spécification rigoureuses avec un raisonnement réel sur les acteurs, les permissions et les cas limites, mais sans implémentation, intégration ni comportement à l'exécution susceptibles de mal tourner.`,
    sections: [
      { heading: "Le mandat", body: `Ce projet consistait à analyser et concevoir un système de partage de fichiers avant l'implémentation. L'objectif était de définir ce que le système devait accomplir, d'identifier comment les différents utilisateurs interagiraient avec lui et de documenter son comportement attendu.` },
      { heading: "Le piège", body: `Une plateforme de partage de fichiers devient rapidement difficile à développer si ses acteurs, permissions, fonctionnalités et flux de travail ne sont pas clairement définis avant l'implémentation.` },
      { heading: "Comment j'ai découpé le problème", body: `J'ai analysé les exigences du système, identifié les acteurs principaux et les cas d'utilisation, créé des diagrammes de cas d'utilisation UML et rédigé des spécifications détaillées expliquant le comportement de chaque interaction majeure.` },
      { heading: "Ma part", body: `J'ai participé à l'analyse des exigences, à l'identification des cas d'utilisation, à la modélisation UML et à la création de spécifications fonctionnelles détaillées.` },
      { heading: "Là où c'est devenu difficile", body: `Transformer une idée de produit large en exigences précises et testables. Chaque cas d'utilisation devait avoir des acteurs clairs, des préconditions, des flux attendus, des scénarios alternatifs et des résultats définis.` },
      { heading: "Ce qui est resté", body: `La vraie compétence ici n'était pas de dessiner des diagrammes, c'était de poser la question à laquelle personne n'avait encore répondu : que se passe-t-il quand deux utilisateurs réclament le même fichier en même temps. La moitié de la spécification est venue de cas comme celui-là, pas d'un gabarit UML suivi à la lettre.` },
    ],
    highlights: ["Identification des acteurs du système","Analyse des exigences fonctionnelles","Diagrammes de cas d'utilisation UML","Descriptions détaillées des cas d'utilisation","Définition des interactions utilisateur","Frontières et responsabilités du système","Documentation préparée pour l'implémentation"],
    stack: ["UML","Use case diagrams","Requirements engineering","System analysis","Technical documentation"],
  },
  {
    slug: "banking-system-api",
    doorNumber: "02",
    order: 2,
    complexity: 3,
    category: "software",
    doorKind: "vault",
    title: "Banking System API",
    type: "Application backend et base de données · Projet d'équipe académique",
    tagline: `Une application backend qui gère l'information bancaire par des points de terminaison REST structurés et une logique de base de données relationnelle.`,
    preview: `Une API REST pour un système bancaire, avec des opérations CRUD sur les comptes et les transactions gérées en SQL et PL/SQL plutôt que remontées dans la couche applicative.`,
    previewStack: "SQL · PL/SQL · JavaScript",
    status: "Delivered",
    links: [{ label: "Dépôt non public", href: "#" }],
    meta: [["Rôle", "API et base de données"], ["Équipe", "En équipe"], ["Année", "2025"], ["Statut", "Livré"]],
    whyRated: `Conception relationnelle, CRUD sur toute la surface de l'API et coordination entre la logique des routes, les requêtes SQL et les procédures stockées, dans un domaine où un mauvais résultat, c'est un mauvais solde.`,
    sections: [
      { heading: "Le cahier des charges", body: `L'API du système bancaire est une application backend conçue pour gérer l'information bancaire par des points de terminaison REST structurés et des opérations sur la base de données.` },
      { heading: "Ce qui devait tenir", body: `Le projet exigeait un moyen fiable de créer, lire, mettre à jour et supprimer des dossiers bancaires tout en maintenant un lien clair entre la couche API et la base de données relationnelle.` },
      { heading: "Comment on l'a construit", body: `Notre équipe a développé des points de terminaison REST pour les opérations principales et les a connectés à la logique SQL et PL/SQL. L'API offrait une interface structurée par laquelle les applications clientes pouvaient interagir avec les données bancaires.` },
      { heading: "Ma part du travail", body: `J'ai contribué à la conception et à l'implémentation des routes de l'API et des opérations sur la base de données. J'ai travaillé avec les requêtes GET, POST, PUT et DELETE et aidé à relier chaque opération à la logique CRUD appropriée.` },
      { heading: "Là où était le risque", body: `Garantir que chaque requête API exécute la bonne opération sur la base de données et retourne un résultat cohérent. Cela exigeait une coordination minutieuse entre la logique des routes, les requêtes SQL et les procédures stockées.` },
      { heading: "La leçon", body: `Un mauvais résultat CRUD dans un système bancaire n'est pas un rapport de bogue, c'est le solde de quelqu'un. Ça a changé ma façon de tester : pas « est-ce que le endpoint répond », mais « est-ce que cette séquence précise d'appels laisse le grand livre dans un état auquel je ferais confiance avec mon propre argent ».` },
    ],
    highlights: ["Structure d'API REST","Points de terminaison GET, POST, PUT et DELETE","Opérations sur base de données relationnelle","Requêtes SQL","Procédures et logique PL/SQL","Fonctionnalité CRUD","Gestion des requêtes et des réponses","Développement en équipe"],
    stack: ["JavaScript","SQL","PL/SQL","Oracle Database","REST APIs"],
  },
  {
    slug: "vamp2-survivors",
    doorNumber: "03",
    order: 3,
    complexity: 3,
    category: "software",
    doorKind: "arch",
    title: "VAMP2 Survivors",
    type: "Jeu de survie 3D · Projet académique",
    tagline: `Un jeu de survie 3D inspiré de Vampire Survivors. Le travail intéressant n'a jamais été le rendu, c'était le comportement des ennemis capable de grandir sans s'effondrer sous les conditions.`,
    preview: `Un jeu de survie 3D dans Unity où le vrai travail était le comportement des ennemis : une machine à états, un système d'événements Observer et une mécanique de leurre bâtie sur une interface de ciblage commune.`,
    previewStack: "C# · Unity · OOP",
    status: "Delivered",
    links: [{ label: "Dépôt non public", href: "#" }],
    meta: [["Rôle", "Programmeur gameplay"], ["Moteur", "Unity"], ["Année", "2026"], ["Statut", "Livré"]],
    whyRated: `Comportement en temps réel, patrons de conception appliqués délibérément et logique de gameplay testée par unités, mais autonome : pas d'intégrations, pas de persistance, pas de surface de sécurité.`,
    sections: [
      { heading: "Le pitch", body: `VAMP2 Survivors est un jeu de survie 3D inspiré de Vampire Survivors. Le joueur survit à des vagues d'ennemis grâce au déplacement, à la stratégie et aux mécaniques de jeu pour maîtriser des rencontres de plus en plus difficiles.` },
      { heading: "Le problème de conception", body: `Le jeu avait besoin d'ennemis capables de changer de comportement proprement, de réagir aux événements et de choisir entre le joueur et d'autres cibles sans créer de code fortement couplé.` },
      { heading: "Ce que j'ai livré", body: `J'ai implémenté le comportement des ennemis avec une machine à états et utilisé le patron Observer orienté événements pour coordonner les réactions. J'ai aussi créé une mécanique de leurre via l'interface ICibleEnnemi, permettant aux ennemis de viser différents objets selon un contrat commun.` },
      { heading: "Mon rôle", body: `J'ai développé le comportement central des ennemis, implémenté le système de leurre, connecté les réactions orientées événements et écrit des tests unitaires pour la logique de gameplay importante.` },
      { heading: "Le piège que j'ai évité", body: `Empêcher la logique ennemie de devenir une grande collection de conditions. Diviser le comportement en états et programmer contre une interface a rendu le système plus facile à étendre, tester et comprendre.` },
      { heading: "Ce que je referais", body: `Une interface prouve sa valeur la première fois qu'on ajoute une fonctionnalité non prévue. Câbler la mécanique de leurre via ICibleEnnemi plutôt que coder en dur une liste de cibles, c'est la décision de ce projet que je reprendrais sans hésiter.` },
    ],
    highlights: ["Comportement ennemi par machine à états","Comportement de gameplay orienté événements","Patron de conception Observer","Sélection de cible basée sur les interfaces","Mécanique de gameplay leurre","Architecture orientée objet","Tests unitaires","Composants réutilisables et maintenables"],
    stack: ["C#","Unity","State machines","Observer pattern","Interfaces","Unit testing"],
  },
  {
    slug: "travel-express",
    doorNumber: "04",
    order: 4,
    complexity: 3,
    category: "fullstack",
    doorKind: "gate",
    title: "Travel Express",
    type: "Application Web de voyage full stack · Projet d'équipe académique",
    tagline: `Une plateforme de voyage full stack où les utilisateurs créent des comptes, explorent destinations et forfaits, gèrent des réservations et enregistrent des favoris. J'ai porté le backend.`,
    preview: `Une plateforme de voyage full stack avec comptes, forfaits, réservations et favoris. J'ai porté le backend : routes API, logique serveur en Node et authentification JWT.`,
    previewStack: "Node.js · React · MongoDB",
    status: "Delivered",
    links: [{ label: "Dépôt non public", href: "#" }],
    meta: [["Rôle", "Développeur backend"], ["Équipe", "En équipe"], ["Année", "2026"], ["Statut", "Livré"]],
    whyRated: `Portée full stack avec authentification, deux technologies de base de données et un vrai flux de travail d'équipe, mais un seul service sans enjeux distribués ni pipelines automatisés derrière.`,
    sections: [
      { heading: "Le point de départ", body: `Travel Express est une plateforme de voyage full stack où les utilisateurs peuvent créer des comptes, explorer des destinations et des forfaits, gérer des réservations, enregistrer des favoris et interagir avec du contenu voyage.` },
      { heading: "Le problème de coordination", body: `Le projet exigeait que l'équipe relie une interface réactive, un backend sécurisé et plusieurs opérations sur les bases de données dans une application cohérente. Les renseignements utilisateur et les actions protégées devaient aussi être gérés de façon sécurisée.` },
      { heading: "Ce qu'on a construit", body: `Nous avons développé une application Web complète avec une interface React, un backend Node.js, des routes API REST, de l'authentification et une persistance en base de données. L'application séparait la présentation frontend de la logique backend et de l'accès aux données.` },
      { heading: "Ce dont j'étais responsable", body: `J'étais principalement responsable du développement backend. J'ai créé les routes API, implémenté la logique côté serveur, intégré la base de données et ajouté l'authentification par JWT. J'ai aussi collaboré avec l'équipe frontend pour définir les structures de requêtes et de réponses.` },
      { heading: "Le point de friction", body: `Maintenir des données et un comportement d'API cohérents pendant que plusieurs membres de l'équipe travaillaient sur différentes parties de l'application. Des définitions de routes claires et un flux de travail Git nous ont permis d'intégrer les composants de façon fiable.` },
      { heading: "Ce que ça a changé", body: `Un contrat REST est une promesse, pas une suggestion. La plupart des frictions sur ce projet n'étaient pas dans le code, mais deux personnes qui supposaient des formes différentes pour la même réponse, et qui le découvraient à l'intégration plutôt qu'avant.` },
    ],
    highlights: ["Inscription et authentification des utilisateurs","Routes protégées par JWT","Gestion des forfaits et des destinations","Fonctionnalité de réservation","Favoris et commentaires","Opérations CRUD RESTful","Intégration frontend et backend","Flux de travail d'équipe avec Git","Opérations sur bases relationnelles et documentaires"],
    stack: ["React","Vite","Bootstrap","Node.js","Express","MongoDB","Oracle","SQL","PL/SQL","JWT"],
  },
  {
    slug: "dossier",
    doorNumber: "05",
    order: 5,
    complexity: 4,
    category: "fullstack",
    doorKind: "lab",
    title: "Dossier",
    type: "Plateforme B2B de recherche et de personnalisation",
    tagline: `Un système de recherche et de personnalisation qui aide les équipes de vente sortantes à bâtir des campagnes de courriel à froid pertinentes à grande échelle, sans sacrifier la précision.`,
    preview: `Un pipeline B2B de recherche et de personnalisation : prospects en entrée, recherche et notation, variantes personnalisées en sortie. Un pilote de 100 prospects a atteint un taux de réponse de 9,6 %.`,
    previewStack: "TypeScript · PostgreSQL · Supabase",
    status: "Live",
    links: [{ label: "Site en ligne ↗", href: "https://rundossier.co", primary: true }, { label: "Dépôt non public", href: "#" }],
    meta: [["Rôle", "Backend et architecture"], ["Année", "2026"], ["Domaine", "Recherche commerciale B2B"], ["Statut", "En ligne"]],
    whyRated: `Orchestration de flux de travail multiphase, intégrations de données externes, notation de la recherche et garde-fous qualité, état des flux dans PostgreSQL, nouvelles tentatives et gestion des lettres mortes, plus surveillance opérationnelle de livraisons réelles.`,
    sections: [
      { heading: "L'idée", body: `Dossier est un système de recherche et de personnalisation conçu pour aider les équipes de vente sortantes à créer des campagnes de courriel à froid pertinentes à grande échelle. Il combine recherche automatisée de prospects, validation des données, notation et génération de courriels personnalisés dans un pipeline de livraison structuré.` },
      { heading: "Pourquoi c'est plus dur qu'il n'y paraît", body: `La plupart des démarches à froid automatisées s'appuient sur de l'information générique et des modèles répétitifs. Rechercher chaque prospect à la main produit une meilleure personnalisation, mais c'est beaucoup trop lent et coûteux pour des campagnes de milliers de prospects.` },
      { heading: "Le pipeline", body: `J'ai bâti un flux de travail multiphase qui collecte les données de prospects, recherche des signaux d'affaires pertinents, note la qualité de cette recherche, génère plusieurs variantes de courriel personnalisées et valide le résultat final avant la livraison.` },
      { heading: "Où je me suis concentré", body: `J'ai conçu l'architecture backend, le modèle de base de données, les flux automatisés, la logique de recherche, le système de notation, le processus de personnalisation et les garde-fous de contrôle qualité. J'ai aussi intégré des sources de données externes et bâti la gestion des échecs pour les tâches incomplètes ou non réussies.` },
      { heading: "Le mode d'échec", body: `Les tâches de recherche externes pouvaient échouer ou retourner de l'information incomplète. J'ai introduit la notation, des états de repli, des nouvelles tentatives et le suivi des lettres mortes pour que les résultats faibles soient identifiés au lieu d'atteindre le client en silence.` },
      { heading: "Ce que ça m'a appris", body: `Un flux mesurable et un flux qui « marche » tout court sont deux objectifs différents. Une fois la notation et le suivi des lettres mortes ajoutés, une personnalisation faible a cessé de se cacher dans un tableur plein de coches vertes : elle est devenue un chiffre sur lequel je pouvais agir.` },
    ],
    result: `Un pilote externe de 100 prospects recherchés a atteint environ 9,6 % de taux de réponse. Une livraison ultérieure de 500 prospects a révélé des leçons plus exigeantes sur la qualité des données, la stratégie de nouvelles tentatives et la surveillance opérationnelle.`,
    highlights: ["Ingestion et déduplication de prospects","Recherche automatisée d'entreprises et de prospects","Notation de la qualité de la recherche","Variantes de courriel personnalisées","Garde-fous de contrôle qualité et de validation","État des flux de travail basé sur PostgreSQL","Nouvelles tentatives et gestion des lettres mortes","Livraison automatisée en CSV","Intégrations d'API externes et de fournisseurs de données","Rapports et surveillance opérationnels"],
    stack: ["TypeScript","Node.js","Express","React","PostgreSQL","Supabase","n8n","Apify"],
  },
  {
    slug: "trade-catch",
    doorNumber: "06",
    order: 6,
    complexity: 4,
    category: "fullstack",
    doorKind: "slat",
    title: "Trade Catch",
    type: "Plateforme d'automatisation d'affaires full stack",
    tagline: `Récupération de prospects et suivi des ventes pour les entrepreneurs et les entreprises de services locaux. Il répond aux appels manqués et relance les soumissions oubliées.`,
    preview: `Les entrepreneurs perdent des contrats à cause d'appels manqués et de soumissions oubliées. Cette plateforme engage l'appelant immédiatement, le qualifie, alerte l'entrepreneur et fait le suivi jusqu'à obtenir une réponse.`,
    previewStack: "Next.js · Cloudflare Workers · Twilio",
    status: "In development",
    statusNote: `La plateforme et l'expérience de démonstration sont en développement actif. Les prochaines étapes visent les intégrations de production, la surveillance, l'analytique et l'intégration d'entreprises réelles.`,
    links: [{ label: "Dépôt non public", href: "#" }],
    meta: [["Rôle", "Concept, produit et automatisation"], ["Année", "2026"], ["Domaine", "Métiers et services à domicile"], ["Statut", "En développement"]],
    whyRated: `Authentification, intégrations téléphonie et paiement, moteur de flux automatisés, déploiement en périphérie, communication client bilingue et frontière nette entre la messagerie et les règles d'affaires déterministes.`,
    sections: [
      { heading: "Le problème dans les métiers", body: `Trade Catch est une plateforme de récupération de prospects et de suivi des ventes pour les entrepreneurs et les entreprises de services locaux. Elle les aide à répondre aux appels manqués, qualifier les clients potentiels, planifier des rendez-vous, relancer les soumissions et suivre les occasions depuis un tableau de bord.` },
      { heading: "Pourquoi ça arrive", body: `Les entrepreneurs perdent des contrats précieux parce qu'ils ne peuvent pas répondre aux appels pendant qu'ils travaillent, oublient de relancer les soumissions ou répondent trop lentement. Le client contacte simplement la prochaine entreprise disponible, et l'entrepreneur perd un revenu sur un prospect qu'il avait déjà généré.` },
      { heading: "La parade", body: `J'ai conçu Trade Catch comme un flux automatisé qui engage immédiatement les appelants manqués, recueille l'information sur le service demandé, alerte l'entrepreneur et oriente les clients qualifiés vers la prise de rendez-vous. Il relance aussi les soumissions jusqu'à ce que le client réponde, réserve le service ou se désinscrive.` },
      { heading: "Ce que j'ai construit", body: `J'ai développé le concept produit, le parcours client, l'expérience du site Web et la logique d'automatisation. J'ai conçu la circulation de l'information entre les interactions client, les flux de qualification, les alertes entrepreneur, la planification et les rapports. J'ai aussi géré le déploiement et la configuration Cloudflare.` },
      { heading: "La ligne que j'ai tracée", body: `Concevoir une automatisation qui paraît immédiate et utile sans devenir imprévisible. J'ai séparé la messagerie et la classification des prospects des règles strictes qui régissent la planification, la tarification, les désinscriptions, la sécurité et l'escalade. Le texte peut varier. Les décisions de facturation et de réservation, non.` },
      { heading: "L'habitude que j'en garde", body: `L'idée à laquelle je revenais sans cesse : l'automatisation peut envoyer le suivi, elle ne décide pas qui est facturé. Chaque demande de fonctionnalité qui brouillait cette frontière a été renvoyée vers une règle déterministe.` },
    ],
    highlights: ["Expérience Web full stack réactive","Communication client bilingue","Récupération d'appels manqués et suivi automatisé","Qualification de prospects et alertes entrepreneur","Flux de prise de rendez-vous","Séquences de suivi de soumissions","Tableau de bord pour suivre prospects et résultats","Séparation claire entre messagerie et règles déterministes"],
    stack: ["Next.js","React","TypeScript","Cloudflare Workers","OpenNext","Twilio","Stripe"],
  },
  {
    slug: "sentinelops",
    doorNumber: "07",
    order: 7,
    complexity: 5,
    category: "software",
    doorKind: "secure",
    title: "SentinelOps",
    type: "Plateforme infonuagique de sécurité et de gestion d'incidents",
    tagline: `Une plateforme pour collecter, analyser et gérer les événements de sécurité, offrant aux analystes un endroit unique pour examiner les alertes, prioriser les incidents et coordonner une réponse.`,
    preview: `Les événements de sécurité arrivent de nombreux systèmes sous de nombreux formats. SentinelOps les normalise en un seul modèle et les fait traverser un flux de gestion d'incidents structuré, pour que les analystes traitent une file priorisée plutôt qu'un torrent.`,
    previewStack: "AWS · ASP.NET Core · Incident response",
    status: "In development",
    statusNote: `SentinelOps est un projet de portfolio en évolution. Les phases à venir incluent des intégrations AWS plus poussées, un enrichissement automatisé, des flux de notification, l'automatisation de l'infrastructure et de l'analytique de sécurité avancée.`,
    links: [{ label: "Dépôt non public", href: "#" }],
    meta: [["Rôle", "Architecture et full stack"], ["Année", "2026"], ["Domaine", "Opérations de sécurité"], ["Statut", "En développement"]],
    whyRated: `Ingestion d'événements infonuagiques, schéma normalisé d'événements de sécurité, flux d'incidents structuré, API authentifiée, persistance relationnelle, journalisation et gestion des échecs, dans un domaine où un bogue a de vraies conséquences. Évalué sur l'architecture et le risque, pas les heures passées.`,
    sections: [
      { heading: "La prémisse", body: `SentinelOps est une plateforme infonuagique pour collecter, analyser et gérer les événements de sécurité. Elle offre aux équipes de sécurité une interface centralisée pour examiner les alertes, prioriser les incidents, suivre les enquêtes et coordonner les réponses.` },
      { heading: "Le problème du bruit", body: `Les événements de sécurité proviennent de nombreux systèmes et arrivent sous des formats différents. Sans normalisation ni priorisation, les équipes peinent à repérer les menaces qui comptent, en comprendre le contexte et répondre de façon cohérente.` },
      { heading: "Le système", body: `SentinelOps transforme les événements entrants en un modèle normalisé d'événements de sécurité et les fait traverser un flux structuré de gestion d'incidents. La plateforme relie le traitement d'événements infonuagique à une API backend, un stockage persistant et un tableau de bord analyste réactif.` },
      { heading: "Mon bout du travail", body: `J'ai conçu l'architecture de la plateforme, le schéma d'événements de sécurité, la structure backend, le flux de traitement infonuagique et l'expérience frontend. Je me suis concentré sur des frontières claires entre ingestion, validation, stockage, analyse et réponse aux incidents.` },
      { heading: "La contrainte forte", body: `Concevoir un système qui traite les événements de façon fiable tout en conservant une traçabilité complète. Chaque événement doit être validé, normalisé et relié à un incident sans perdre l'information dont un analyste a besoin pour enquêter.` },
      { heading: "Le changement de perspective", body: `Les outils de sécurité échouent en silence si on les laisse faire. L'habitude que je garde de ce projet : concevoir pour l'analyste fatigué à 3h du matin, moins d'alertes, mais chacune traçable jusqu'à l'événement brut qui l'a déclenchée.` },
    ],
    highlights: ["Schéma normalisé d'événements de sécurité","Ingestion et traitement d'événements infonuagiques","Création, priorisation et suivi d'état des incidents","API backend structurée","Tableau de bord analyste en React","Persistance PostgreSQL","Authentification, validation et réponses normalisées","Journalisation, gestion des erreurs et documentation API","Infrastructure conçue pour la montée en charge et l'automatisation future"],
    stack: ["AWS","ASP.NET Core","C#","React","PostgreSQL","REST APIs"],
  },
];

export function getProjectFr(slug: string) {
  return projectsFr.find((p) => p.slug === slug);
}
