import type { Project } from '@/lib/types';

export const projectsEn: Project[] = [
  {
    slug: 'file-sharing-system',
    doorNumber: '01',
    order: 1,
    complexity: 2,
    doorKind: 'blueprint',
    title: 'File Sharing System',
    type: 'Software analysis and system design project',
    tagline: `Analysis and design of a file sharing system before implementation. No code, which was the point: the deliverable was a specification precise enough to build from.`,
    preview: `Use case driven analysis of a multi user file sharing system, taken from actor diagrams to a written specification a team could build from.`,
    previewStack: 'UML · Specification · Design',
    status: 'Delivered',
    links: [],
    meta: [['Role', 'Analysis and design'], ['Method', 'UML use cases'], ['Year', '2026'], ['Status', 'Delivered']],
    whyRated: `Rigorous modelling and specification work with real reasoning about actors, permissions and edge cases, but no implementation, integration or runtime behaviour to get wrong.`,
    sections: [
      { heading: 'Overview', body: `This project involved analyzing and designing a file sharing system before implementation. The objective was to define what the system should accomplish, identify how different users would interact with it and document its expected behavior.` },
      { heading: 'The problem', body: `A file sharing platform quickly becomes difficult to develop if its actors, permissions, features and workflows are not clearly defined before implementation.` },
      { heading: 'The solution', body: `I analyzed the system requirements, identified the principal actors and use cases, created UML use case diagrams and wrote detailed specifications explaining the behavior of each major interaction.` },
      { heading: 'My contribution', body: `I participated in requirements analysis, use case identification, UML modeling and the creation of detailed functional specifications.` },
      { heading: 'Key challenge', body: `Turning a broad product idea into precise and testable requirements. Each use case needed clear actors, preconditions, expected flows, alternative scenarios and outcomes.` },
      { heading: 'What I learned', body: `That software engineering begins before code is written. I developed a stronger understanding of requirements analysis, system modeling, technical communication and how clear specifications reduce ambiguity during development.` },
    ],
    highlights: ["Identification of system actors","Functional requirement analysis","UML use case diagrams","Detailed use case descriptions","Definition of user interactions","System boundaries and responsibilities","Documentation prepared for implementation"],
    stack: ["UML","Use case diagrams","Requirements engineering","System analysis","Technical documentation"],
  },
  {
    slug: 'banking-system-api',
    doorNumber: '02',
    order: 2,
    complexity: 3,
    doorKind: 'vault',
    title: 'Banking System API',
    type: 'Backend and database application · Academic team project',
    tagline: `A backend application managing banking information through structured REST endpoints and relational database logic.`,
    preview: `A REST API for a banking system, with CRUD over accounts and transactions handled in SQL and PL/SQL rather than pushed up into the application layer.`,
    previewStack: 'SQL · PL/SQL · JavaScript',
    status: 'Delivered',
    links: [{ label: 'Repository not public', href: '#' }],
    meta: [['Role', 'API and database'], ['Team', 'Collaborative'], ['Year', '2025'], ['Status', 'Delivered']],
    whyRated: `Relational design, CRUD across a full API surface and coordination between route logic, SQL queries and stored procedures, in a domain where a wrong result is a wrong balance.`,
    sections: [
      { heading: 'Overview', body: `The Banking System API is a backend application designed to manage banking information through structured REST endpoints and database operations.` },
      { heading: 'The problem', body: `The project required a reliable way to create, retrieve, update and delete banking records while maintaining a clear connection between the API layer and the relational database.` },
      { heading: 'The solution', body: `Our team developed REST endpoints for the principal operations and connected them to SQL and PL/SQL database logic. The API provided a structured interface through which client applications could interact with the banking data.` },
      { heading: 'My contribution', body: `I contributed to the design and implementation of the API routes and database operations. I worked with GET, POST, PUT and DELETE requests and helped connect each operation to the appropriate CRUD logic.` },
      { heading: 'Key challenge', body: `Ensuring that every API request performed the correct database operation and returned a consistent result. That required careful coordination between route logic, SQL queries and stored procedures.` },
      { heading: 'What I learned', body: `This project strengthened my understanding of backend development, relational databases, REST conventions and the relationship between application code and database logic. It also gave me more experience designing and testing CRUD operations.` },
    ],
    highlights: ["REST API structure","GET, POST, PUT and DELETE endpoints","Relational database operations","SQL queries","PL/SQL procedures and logic","CRUD functionality","Request and response handling","Team based development"],
    stack: ["JavaScript","SQL","PL/SQL","Oracle Database","REST APIs"],
  },
  {
    slug: 'vamp2-survivors',
    doorNumber: '03',
    order: 3,
    complexity: 3,
    doorKind: 'arch',
    title: 'VAMP2 Survivors',
    type: '3D survival game · Academic project',
    tagline: `A 3D survival game inspired by Vampire Survivors. The interesting work was never the rendering, it was enemy behaviour that could grow without collapsing into conditions.`,
    preview: `A 3D survival game in Unity where the real work was enemy behaviour: a state machine, an Observer driven event system, and a decoy mechanic built on a shared targeting interface.`,
    previewStack: 'C# · Unity · OOP',
    status: 'Delivered',
    links: [{ label: 'Repository not public', href: '#' }],
    meta: [['Role', 'Gameplay programmer'], ['Engine', 'Unity'], ['Year', '2026'], ['Status', 'Delivered']],
    whyRated: `Real time behaviour, design patterns applied deliberately and unit tested gameplay logic, but self contained: no integrations, no persistence, no security surface.`,
    sections: [
      { heading: 'Overview', body: `VAMP2 Survivors is a 3D survival game inspired by Vampire Survivors. The player survives repeated enemy attacks using movement, strategy and game mechanics to control increasingly difficult encounters.` },
      { heading: 'The problem', body: `The game needed enemies that could change behavior cleanly, react to events and select between the player and alternative targets without creating tightly coupled code.` },
      { heading: 'The solution', body: `I implemented enemy behavior using a state machine and used an event driven Observer pattern to coordinate reactions. I also created a decoy mechanic through the ICibleEnnemi interface, allowing enemies to target different objects through a shared contract.` },
      { heading: 'My contribution', body: `I developed core enemy behavior, implemented the decoy system, connected event driven reactions and wrote unit tests for important gameplay logic.` },
      { heading: 'Key challenge', body: `Preventing enemy logic from becoming one large collection of conditions. Dividing behavior into states and programming against an interface made the system easier to extend, test and understand.` },
      { heading: 'What I learned', body: `This project improved my understanding of object oriented design, design patterns, game state management, event driven programming and automated testing. It showed me how good architecture makes gameplay systems easier to expand.` },
    ],
    highlights: ["State machine enemy artificial intelligence","Event driven gameplay behavior","Observer design pattern","Interface based target selection","Decoy gameplay mechanic","Object oriented architecture","Unit testing","Reusable and maintainable components"],
    stack: ["C#","Unity","State machines","Observer pattern","Interfaces","Unit testing"],
  },
  {
    slug: 'travel-express',
    doorNumber: '04',
    order: 4,
    complexity: 3,
    doorKind: 'gate',
    title: 'Travel Express',
    type: 'Full stack travel web application · Academic team project',
    tagline: `A full stack travel platform where users create accounts, explore destinations and packages, manage reservations and save favorites. I owned the backend.`,
    preview: `A full stack travel platform with accounts, packages, reservations and favorites. I owned the backend: API routes, server logic in Node and JWT authentication.`,
    previewStack: 'Node.js · React · MongoDB',
    status: 'Delivered',
    links: [{ label: 'Repository not public', href: '#' }],
    meta: [['Role', 'Backend developer'], ['Team', 'Collaborative'], ['Year', '2026'], ['Status', 'Delivered']],
    whyRated: `Full stack scope with authentication, two database technologies and a real team workflow, but a single service with no distributed concerns or automated pipelines behind it.`,
    sections: [
      { heading: 'Overview', body: `Travel Express is a full stack travel platform where users can create accounts, explore destinations and travel packages, manage reservations, save favorites and interact with travel content.` },
      { heading: 'The problem', body: `The project required our team to connect a responsive frontend, a secure backend and multiple database operations within one consistent application. User information and protected actions also needed to be managed securely.` },
      { heading: 'The solution', body: `We developed a complete web application with a React interface, a Node.js backend, REST API routes, authentication and database persistence. The application separated frontend presentation from backend logic and data access.` },
      { heading: 'My contribution', body: `I was primarily responsible for backend development. I created API routes, implemented server side logic, integrated the database and added JWT based authentication. I also collaborated with the frontend team to define request and response structures.` },
      { heading: 'Key challenge', body: `Maintaining consistent data and API behavior while several team members worked on different parts of the application. Clear route definitions and a Git workflow let us integrate the components reliably.` },
      { heading: 'What I learned', body: `Travel Express gave me practical experience building a complete web application as part of a team. I strengthened my knowledge of backend architecture, authentication, database integration, REST APIs, debugging and collaborative development.` },
    ],
    highlights: ["User registration and authentication","JWT protected routes","Travel package and destination management","Reservation functionality","Favorites and comments","RESTful CRUD operations","Frontend and backend integration","Git based team workflow","Relational and document database operations"],
    stack: ["React","Vite","Bootstrap","Node.js","Express","MongoDB","Oracle","SQL","PL/SQL","JWT"],
  },
  {
    slug: 'dossier',
    doorNumber: '05',
    order: 5,
    complexity: 4,
    doorKind: 'lab',
    title: 'Dossier',
    type: 'AI powered B2B research and personalization platform',
    tagline: `A research and personalization system that helps outbound sales teams build relevant cold email campaigns at scale, without giving up on accuracy.`,
    preview: `A B2B research and personalization pipeline: prospects in, researched and scored, personalized variants out. A 100 prospect pilot reached a 9.6% reply rate.`,
    previewStack: 'TypeScript · PostgreSQL · Claude API',
    status: 'Live',
    links: [{ label: 'Live site ↗', href: 'https://rundossier.co', primary: true }, { label: 'Repository not public', href: '#' }],
    meta: [['Role', 'Backend and architecture'], ['Year', '2026'], ['Domain', 'B2B sales research'], ['Status', 'Live']],
    whyRated: `Multi stage AI workflow orchestration, external data integrations, research scoring and quality gates, workflow state in PostgreSQL, retries and dead letter handling, plus operational monitoring of real deliveries.`,
    sections: [
      { heading: 'Overview', body: `Dossier is a research and personalization system designed to help outbound sales teams create relevant cold email campaigns at scale. It combines automated prospect research, data validation, scoring and AI generated personalization into a structured delivery pipeline.` },
      { heading: 'The problem', body: `Most automated cold outreach relies on generic information and repetitive AI generated messages. Researching every prospect by hand produces better personalization, but it is far too slow and expensive for campaigns of thousands of prospects.` },
      { heading: 'The solution', body: `I built a multi stage workflow that collects prospect data, researches relevant business signals, scores the quality of that research, generates several personalized email variants and validates the final output before delivery.` },
      { heading: 'My contribution', body: `I designed the backend architecture, database model, automated workflows, research logic, scoring system, personalization process and quality control gates. I also integrated external data sources and built failure handling for incomplete or unsuccessful jobs.` },
      { heading: 'Key challenge', body: `External research jobs could fail or return incomplete information. I introduced scoring, fallback states, retries and dead letter tracking so weak results could be identified instead of silently reaching the customer.` },
      { heading: 'What I learned', body: `Dossier taught me how to build multi step AI workflows that stay measurable and controllable. I gained experience with data pipelines, external APIs, prompt design, quality assurance, database state management and production failure analysis.` },
    ],
    result: `An external pilot of 100 researched prospects reached roughly a 9.6% reply rate. A later 500 prospect delivery surfaced harder lessons about data quality, retry strategy and operational monitoring.`,
    highlights: ["Prospect ingestion and deduplication","Automated company and prospect research","Research quality scoring","AI generated personalization variants","Quality control and validation gates","PostgreSQL based workflow state","Retry and dead letter handling","Automated CSV delivery","External API and data provider integrations","Operational reporting and monitoring"],
    stack: ["TypeScript","Node.js","Express","React","PostgreSQL","Supabase","n8n","Claude API","Apify"],
  },
  {
    slug: 'trade-catch',
    doorNumber: '06',
    order: 6,
    complexity: 4,
    doorKind: 'slat',
    title: 'Trade Catch',
    type: 'Full stack business automation platform',
    tagline: `Lead recovery and sales follow up for contractors and local service businesses. It answers the calls they miss and chases the estimates they forget.`,
    preview: `Contractors lose jobs to missed calls and forgotten estimates. This platform engages the caller immediately, qualifies them, alerts the contractor and follows up until there is an answer.`,
    previewStack: 'Next.js · Cloudflare Workers · Twilio',
    status: 'In development',
    statusNote: `The platform and demonstration experience are under active development. Future work focuses on production integrations, monitoring, analytics and onboarding real businesses.`,
    links: [{ label: 'Repository not public', href: '#' }],
    meta: [['Role', 'Concept, product and automation'], ['Year', '2026'], ['Domain', 'Trades and home services'], ['Status', 'In development']],
    whyRated: `Authentication, telephony and payment integrations, an automated workflow engine, edge deployment, bilingual customer communication and a hard boundary between AI assisted language and deterministic business rules.`,
    sections: [
      { heading: 'Overview', body: `Trade Catch is a lead recovery and sales follow up platform for contractors and local service businesses. It helps them respond to missed calls, qualify potential customers, schedule appointments, follow up on estimates and track opportunities from one dashboard.` },
      { heading: 'The problem', body: `Contractors lose valuable jobs because they cannot answer calls while working, forget to follow up on estimates, or respond too slowly. The customer simply contacts the next available company, and the contractor loses revenue on a lead they already generated.` },
      { heading: 'The solution', body: `I designed Trade Catch as an automated workflow that engages missed callers immediately, collects information about the requested service, alerts the contractor and guides qualified customers toward booking. It also follows up on estimates until the customer responds, books the service or opts out.` },
      { heading: 'My contribution', body: `I developed the product concept, customer journey, website experience and automation logic. I designed how information moves between customer interactions, qualification workflows, contractor alerts, scheduling and reporting. I also handled deployment and Cloudflare configuration.` },
      { heading: 'Key challenge', body: `Designing automation that feels immediate and helpful without becoming unpredictable. I separated AI assisted language and classification from strict rules governing scheduling, pricing, opt outs, safety and escalation. The model can phrase a message. It cannot decide who gets charged.` },
      { heading: 'What I learned', body: `This project strengthened my ability to translate a real business problem into a complete technical product. I learned about workflow design, external integrations, deployment, error handling, conversion focused UX and the importance of keeping critical automation deterministic.` },
    ],
    highlights: ["Responsive full stack web experience","Bilingual customer communication","Missed call recovery and automated follow up","Lead qualification and contractor alerts","Appointment booking workflow","Estimate follow up sequences","Dashboard for monitoring leads and outcomes","Clear separation between AI assisted tasks and deterministic rules"],
    stack: ["Next.js","React","TypeScript","Cloudflare Workers","OpenNext","Twilio","Stripe"],
  },
  {
    slug: 'sentinelops',
    doorNumber: '07',
    order: 7,
    complexity: 5,
    doorKind: 'secure',
    title: 'SentinelOps',
    type: 'Cloud native security and incident management platform',
    tagline: `A platform for collecting, analyzing and managing security events, giving analysts one place to review alerts, prioritize incidents and coordinate a response.`,
    preview: `Security events arrive from many systems in many formats. SentinelOps normalises them into one model and moves them through a structured incident workflow, so analysts work a ranked queue instead of a firehose.`,
    previewStack: 'AWS · ASP.NET Core · Incident response',
    status: 'In development',
    statusNote: `SentinelOps is an evolving portfolio project. Future phases include deeper AWS integrations, automated enrichment, notification workflows, infrastructure automation and advanced security analytics.`,
    links: [{ label: 'Repository not public', href: '#' }],
    meta: [['Role', 'Architecture and full stack'], ['Year', '2026'], ['Domain', 'Security operations'], ['Status', 'In development']],
    whyRated: `Cloud event ingestion, a normalized security event schema, structured incident workflow, authenticated API, relational persistence, logging and failure handling, in a domain where a bug has real consequences. Scored on architecture and risk, not hours spent.`,
    sections: [
      { heading: 'Overview', body: `SentinelOps is a cloud native platform for collecting, analyzing and managing security events. It gives security teams a centralized interface for reviewing alerts, prioritizing incidents, tracking investigations and coordinating responses.` },
      { heading: 'The problem', body: `Security events originate from many systems and arrive in different formats. Without normalization and prioritization, teams struggle to identify the threats that matter, understand their context and respond consistently.` },
      { heading: 'The solution', body: `SentinelOps transforms incoming events into a standardized security event model and moves them through a structured incident management workflow. The platform connects cloud event processing to a backend API, persistent storage and a responsive analyst dashboard.` },
      { heading: 'My contribution', body: `I designed the platform architecture, security event schema, backend structure, cloud processing workflow and frontend experience. I focused on drawing clear boundaries between event ingestion, validation, storage, analysis and incident response.` },
      { heading: 'Key challenge', body: `Designing a system that processes events reliably while keeping full traceability. Every event has to be validated, normalized and connected to an incident without losing the information an analyst needs to investigate it.` },
      { heading: 'What I learned', body: `SentinelOps expanded my understanding of cloud architecture, secure API design, event driven systems, structured logging, failure handling and incident management workflows. It also taught me to look at a system from both an engineering and a security operations perspective.` },
    ],
    highlights: ["Standardized security event schema","Cloud based event ingestion and processing","Incident creation, prioritization and status tracking","Structured backend API","Analyst facing React dashboard","PostgreSQL persistence","Authentication, validation and standardized responses","Logging, error handling and API documentation","Infrastructure designed for scale and future automation"],
    stack: ["AWS","ASP.NET Core","C#","React","PostgreSQL","REST APIs"],
  },
];

export function getProjectEn(slug: string) {
  return projectsEn.find((p) => p.slug === slug);
}
