import type { Project } from '@/lib/types';

export const projectsEn: Project[] = [
  {
    slug: 'file-sharing-system',
    doorNumber: '01',
    order: 1,
    complexity: 2,
    category: 'software',
    doorKind: 'blueprint',
    title: 'File Sharing System',
    type: 'Software analysis and system design project',
    tagline: `Analysis and design of a file sharing system before implementation. No code, which was the point: the deliverable was a specification precise enough to build from.`,
    preview: `Use case driven analysis of a multi user file sharing system, taken from actor diagrams to a written specification a team could build from.`,
    previewStack: 'UML · Specification · Design',
    status: 'Delivered',
    links: [],
    meta: [['Role', 'Analysis and design'], ['Method', 'UML use cases'], ['Year', '2026'], ['Status', 'Delivered']],
    whyRated: `Rigorous modelling and specification work with real reasoning about actors, permissions and edge cases, but no implementation, integration or runtime behaviour to get wrong.`,
    sections: [
      { heading: 'The assignment', body: `This project involved analyzing and designing a file sharing system before implementation. The objective was to define what the system should accomplish, identify how different users would interact with it and document its expected behavior.` },
      { heading: 'The trap', body: `A file sharing platform quickly becomes difficult to develop if its actors, permissions, features and workflows are not clearly defined before implementation.` },
      { heading: 'How I broke it down', body: `I analyzed the system requirements, identified the principal actors and use cases, created UML use case diagrams and wrote detailed specifications explaining the behavior of each major interaction.` },
      { heading: 'My part', body: `I participated in requirements analysis, use case identification, UML modeling and the creation of detailed functional specifications.` },
      { heading: 'Where it actually got hard', body: `Turning a broad product idea into precise and testable requirements. Each use case needed clear actors, preconditions, expected flows, alternative scenarios and outcomes.` },
      { heading: 'What stuck', body: `The actual skill here was not drawing diagrams, it was asking the question nobody had answered yet: what happens when two users claim the same file at once. Half the spec came from chasing edge cases like that, not from following a UML checklist.` },
    ],
    highlights: ["Identification of system actors","Functional requirement analysis","UML use case diagrams","Detailed use case descriptions","Definition of user interactions","System boundaries and responsibilities","Documentation prepared for implementation"],
    stack: ["UML","Use case diagrams","Requirements engineering","System analysis","Technical documentation"],
  },
  {
    slug: 'banking-system-api',
    doorNumber: '02',
    order: 2,
    complexity: 3,
    category: 'software',
    doorKind: 'vault',
    title: 'Banking System API',
    type: 'Backend and database application · Academic team project',
    tagline: `A backend application managing banking information through structured REST endpoints and relational database logic.`,
    preview: `A REST API for a banking system, with CRUD over accounts and transactions handled in SQL and PL/SQL rather than pushed up into the application layer.`,
    previewStack: 'SQL · PL/SQL · JavaScript',
    status: 'Delivered',
    links: [{ label: 'Repository not public', href: '#' }],
    meta: [['Role', 'API and database'], ['Team', 'Collaborative'], ['Year', '2025'], ['Status', 'Delivered']],
    whyRated: `Relational design, CRUD across a full API surface and coordination between route logic, SQL queries and stored procedures, in a domain where a wrong result is a wrong balance.`,
    sections: [
      { heading: 'The brief', body: `The Banking System API is a backend application designed to manage banking information through structured REST endpoints and database operations.` },
      { heading: 'What had to hold', body: `The project required a reliable way to create, retrieve, update and delete banking records while maintaining a clear connection between the API layer and the relational database.` },
      { heading: 'How we built it', body: `Our team developed REST endpoints for the principal operations and connected them to SQL and PL/SQL database logic. The API provided a structured interface through which client applications could interact with the banking data.` },
      { heading: 'My slice of it', body: `I contributed to the design and implementation of the API routes and database operations. I worked with GET, POST, PUT and DELETE requests and helped connect each operation to the appropriate CRUD logic.` },
      { heading: 'Where the risk was', body: `Ensuring that every API request performed the correct database operation and returned a consistent result. That required careful coordination between route logic, SQL queries and stored procedures.` },
      { heading: 'The lesson', body: `A wrong CRUD result in a banking system is not a bug report, it is someone's balance. That changed how I tested: not "does the endpoint respond" but "does this exact sequence of calls leave the ledger in a state I would trust with my own money."` },
    ],
    highlights: ["REST API structure","GET, POST, PUT and DELETE endpoints","Relational database operations","SQL queries","PL/SQL procedures and logic","CRUD functionality","Request and response handling","Team based development"],
    stack: ["JavaScript","SQL","PL/SQL","Oracle Database","REST APIs"],
  },
  {
    slug: 'vamp2-survivors',
    doorNumber: '03',
    order: 3,
    complexity: 3,
    category: 'software',
    doorKind: 'arch',
    title: 'VAMP2 Survivors',
    type: '3D survival game · Academic project',
    tagline: `A 3D survival game inspired by Vampire Survivors. The interesting work was never the rendering, it was enemy behaviour that could grow without collapsing into conditions.`,
    preview: `A 3D survival game in Unity where the real work was enemy behaviour: a state machine, an Observer driven event system, and a decoy mechanic built on a shared targeting interface.`,
    previewStack: 'C# · Unity · OOP',
    status: 'Delivered',
    links: [{ label: 'Repository not public', href: '#' }],
    meta: [['Role', 'Gameplay programmer'], ['Engine', 'Unity'], ['Year', '2026'], ['Status', 'Delivered']],
    whyRated: `Real time behaviour, design patterns applied deliberately and unit tested gameplay logic, but self contained: no integrations, no persistence, no security surface.`,
    sections: [
      { heading: 'The pitch', body: `VAMP2 Survivors is a 3D survival game inspired by Vampire Survivors. The player survives repeated enemy attacks using movement, strategy and game mechanics to control increasingly difficult encounters.` },
      { heading: 'The design problem', body: `The game needed enemies that could change behavior cleanly, react to events and select between the player and alternative targets without creating tightly coupled code.` },
      { heading: 'What I shipped', body: `I implemented enemy behavior using a state machine and used an event driven Observer pattern to coordinate reactions. I also created a decoy mechanic through the ICibleEnnemi interface, allowing enemies to target different objects through a shared contract.` },
      { heading: 'My role', body: `I developed core enemy behavior, implemented the decoy system, connected event driven reactions and wrote unit tests for important gameplay logic.` },
      { heading: 'The trap I avoided', body: `Preventing enemy logic from becoming one large collection of conditions. Dividing behavior into states and programming against an interface made the system easier to extend, test and understand.` },
      { heading: "What I'd keep", body: `An interface earns its keep the first time you add a feature you did not plan for. Wiring the decoy mechanic through ICibleEnnemi instead of hardcoding a target list is the one decision from this project I would make again without hesitation.` },
    ],
    highlights: ["State machine enemy behaviour","Event driven gameplay behavior","Observer design pattern","Interface based target selection","Decoy gameplay mechanic","Object oriented architecture","Unit testing","Reusable and maintainable components"],
    stack: ["C#","Unity","State machines","Observer pattern","Interfaces","Unit testing"],
  },
  {
    slug: 'travel-express',
    doorNumber: '04',
    order: 4,
    complexity: 3,
    category: 'fullstack',
    doorKind: 'gate',
    title: 'Travel Express',
    type: 'Full stack travel web application · Academic team project',
    tagline: `A full stack travel platform where users create accounts, explore destinations and packages, manage reservations and save favorites. I owned the backend.`,
    preview: `A full stack travel platform with accounts, packages, reservations and favorites. I owned the backend: API routes, server logic in Node and JWT authentication.`,
    previewStack: 'Node.js · React · MongoDB',
    status: 'Delivered',
    links: [{ label: 'Repository not public', href: '#' }],
    meta: [['Role', 'Backend developer'], ['Team', 'Collaborative'], ['Year', '2026'], ['Status', 'Delivered']],
    whyRated: `Full stack scope with authentication, two database technologies and a real team workflow, but a single service with no distributed concerns or automated pipelines behind it.`,
    sections: [
      { heading: 'The setup', body: `Travel Express is a full stack travel platform where users can create accounts, explore destinations and travel packages, manage reservations, save favorites and interact with travel content.` },
      { heading: 'The coordination problem', body: `The project required our team to connect a responsive frontend, a secure backend and multiple database operations within one consistent application. User information and protected actions also needed to be managed securely.` },
      { heading: 'What we built', body: `We developed a complete web application with a React interface, a Node.js backend, REST API routes, authentication and database persistence. The application separated frontend presentation from backend logic and data access.` },
      { heading: 'What I owned', body: `I was primarily responsible for backend development. I created API routes, implemented server side logic, integrated the database and added JWT based authentication. I also collaborated with the frontend team to define request and response structures.` },
      { heading: 'The friction point', body: `Maintaining consistent data and API behavior while several team members worked on different parts of the application. Clear route definitions and a Git workflow let us integrate the components reliably.` },
      { heading: 'What changed', body: `A REST contract is a promise, not a suggestion. Most of the friction on this project was not code, it was two people assuming different shapes for the same response and finding out during integration instead of before.` },
    ],
    highlights: ["User registration and authentication","JWT protected routes","Travel package and destination management","Reservation functionality","Favorites and comments","RESTful CRUD operations","Frontend and backend integration","Git based team workflow","Relational and document database operations"],
    stack: ["React","Vite","Bootstrap","Node.js","Express","MongoDB","Oracle","SQL","PL/SQL","JWT"],
  },
  {
    slug: 'dossier',
    doorNumber: '05',
    order: 5,
    complexity: 4,
    category: 'fullstack',
    doorKind: 'lab',
    title: 'Dossier',
    type: 'B2B research and personalization platform',
    tagline: `A research and personalization system that helps outbound sales teams build relevant cold email campaigns at scale, without giving up on accuracy.`,
    preview: `A B2B research and personalization pipeline: prospects in, researched and scored, personalized variants out. A 100 prospect pilot reached a 9.6% reply rate.`,
    previewStack: 'TypeScript · PostgreSQL · Supabase',
    status: 'Live',
    links: [{ label: 'Live site ↗', href: 'https://rundossier.co', primary: true }, { label: 'Repository not public', href: '#' }],
    meta: [['Role', 'Backend and architecture'], ['Year', '2026'], ['Domain', 'B2B sales research'], ['Status', 'Live']],
    whyRated: `Multi stage workflow orchestration, external data integrations, research scoring and quality gates, workflow state in PostgreSQL, retries and dead letter handling, plus operational monitoring of real deliveries.`,
    sections: [
      { heading: 'The idea', body: `Dossier is a research and personalization system designed to help outbound sales teams create relevant cold email campaigns at scale. It combines automated prospect research, data validation, scoring and personalized email generation into a structured delivery pipeline.` },
      { heading: "Why it's harder than it sounds", body: `Most automated cold outreach relies on generic information and repetitive templates. Researching every prospect by hand produces better personalization, but it is far too slow and expensive for campaigns of thousands of prospects.` },
      { heading: 'The pipeline', body: `I built a multi stage workflow that collects prospect data, researches relevant business signals, scores the quality of that research, generates several personalized email variants and validates the final output before delivery.` },
      { heading: 'Where I focused', body: `I designed the backend architecture, database model, automated workflows, research logic, scoring system, personalization process and quality control gates. I also integrated external data sources and built failure handling for incomplete or unsuccessful jobs.` },
      { heading: 'The failure mode', body: `External research jobs could fail or return incomplete information. I introduced scoring, fallback states, retries and dead letter tracking so weak results could be identified instead of silently reaching the customer.` },
      { heading: 'What it taught me', body: `A measurable workflow and a workflow that just "works" are two different goals. Once I added scoring and dead letter tracking, weak personalization stopped hiding in a spreadsheet full of green checkmarks and became a number I could act on.` },
    ],
    result: `An external pilot of 100 researched prospects reached roughly a 9.6% reply rate. A later 500 prospect delivery surfaced harder lessons about data quality, retry strategy and operational monitoring.`,
    highlights: ["Prospect ingestion and deduplication","Automated company and prospect research","Research quality scoring","Personalized email variants","Quality control and validation gates","PostgreSQL based workflow state","Retry and dead letter handling","Automated CSV delivery","External API and data provider integrations","Operational reporting and monitoring"],
    stack: ["TypeScript","Node.js","Express","React","PostgreSQL","Supabase","n8n","Apify"],
  },
  {
    slug: 'trade-catch',
    doorNumber: '06',
    order: 6,
    complexity: 4,
    category: 'fullstack',
    doorKind: 'slat',
    title: 'Trade Catch',
    type: 'Full stack business automation platform',
    tagline: `Lead recovery and sales follow up for contractors and local service businesses. It answers the calls they miss and chases the estimates they forget.`,
    preview: `Contractors lose jobs to missed calls and forgotten estimates. This platform engages the caller immediately, qualifies them, alerts the contractor and follows up until there is an answer.`,
    previewStack: 'Next.js · Cloudflare Workers · Twilio',
    status: 'Public',
    statusNote: `The platform and demonstration experience are under active development. Future work focuses on production integrations, monitoring, analytics and onboarding real businesses.`,
    links: [{ label: 'Repository ↗', href: 'https://github.com/AraGhah/TradeCatch', primary: true }],
    meta: [['Role', 'Concept, product and automation'], ['Year', '2026'], ['Domain', 'Trades and home services'], ['Status', 'Public']],
    whyRated: `Authentication, telephony and payment integrations, an automated workflow engine, edge deployment, bilingual customer communication and a clear boundary between messaging and deterministic business rules.`,
    sections: [
      { heading: 'The problem in the trades', body: `Trade Catch is a lead recovery and sales follow up platform for contractors and local service businesses. It helps them respond to missed calls, qualify potential customers, schedule appointments, follow up on estimates and track opportunities from one dashboard.` },
      { heading: 'Why it happens', body: `Contractors lose valuable jobs because they cannot answer calls while working, forget to follow up on estimates, or respond too slowly. The customer simply contacts the next available company, and the contractor loses revenue on a lead they already generated.` },
      { heading: 'The fix', body: `I designed Trade Catch as an automated workflow that engages missed callers immediately, collects information about the requested service, alerts the contractor and guides qualified customers toward booking. It also follows up on estimates until the customer responds, books the service or opts out.` },
      { heading: 'What I built', body: `I developed the product concept, customer journey, website experience and automation logic. I designed how information moves between customer interactions, qualification workflows, contractor alerts, scheduling and reporting. I also handled deployment and Cloudflare configuration.` },
      { heading: 'The line I drew', body: `Designing automation that feels immediate and helpful without becoming unpredictable. I kept messaging and lead classification separate from strict rules governing scheduling, pricing, opt outs, safety and escalation. Soft copy can vary. Billing and booking decisions cannot.` },
      { heading: 'The habit it left me with', body: `The line I kept coming back to: automation can send the follow-up, it does not get to decide who gets charged. Every feature request that blurred that boundary got pushed back into a deterministic rule instead.` },
    ],
    highlights: ["Responsive full stack web experience","Bilingual customer communication","Missed call recovery and automated follow up","Lead qualification and contractor alerts","Appointment booking workflow","Estimate follow up sequences","Dashboard for monitoring leads and outcomes","Clear separation between messaging and deterministic rules"],
    stack: ["Next.js","React","TypeScript","Cloudflare Workers","OpenNext","Twilio","Stripe"],
  },
  {
    slug: 'internship-desk',
    doorNumber: '07',
    order: 7,
    complexity: 4,
    category: 'fullstack',
    doorKind: 'gate',
    title: 'Internship Desk',
    type: 'AI powered internship platform · Personal project',
    tagline: `A platform designed to centralize and automate internship discovery, application preparation, recruiter outreach and application tracking.`,
    preview: `One workflow for finding internships, matching them to a CV, researching recruiters, drafting applications specific to each role and tracking follow ups, with the important decisions kept visible.`,
    previewStack: 'Full stack · AI automation · Workflows',
    status: 'Public',
    links: [{ label: 'Repository ↗', href: 'https://github.com/AraGhah/CareersAgents', primary: true }],
    meta: [['Role', 'Full stack development and AI automation'], ['Team', 'Individual'], ['Year', '2026'], ['Status', 'Public']],
    whyRated: `Automated discovery, CV based matching, recruiter research, AI generated applications and follow up tracking in one workflow, where a wrong match or a wrong contact costs more than applying by hand.`,
    sections: [
      { heading: 'The brief', body: `Internship Desk is a platform built to reduce the repetitive work involved in finding and managing internship applications. It brings job discovery, CV management, personalized applications, recruiter research and follow ups into one workflow.` },
      { heading: 'What had to hold', body: `Automation could not come at the cost of relevance. Every internship had to match the candidate's profile, while generated emails and cover letters needed to remain specific to the company and position instead of becoming generic AI output.` },
      { heading: 'How I built it', body: `I designed and developed the platform as an individual project, combining a web interface with automated workflows for internship discovery, CV based matching, recruiter research, personalized application generation and follow up tracking.` },
      { heading: 'My slice of it', body: `I handled the full project, from the interface and application flow to the automation architecture and AI assisted features.` },
      { heading: 'Where the risk was', body: `The main risk was incorrect automation. Finding the wrong contact, applying to an irrelevant position or generating inaccurate information would make the system less useful than applying manually.` },
      { heading: 'The lesson', body: `Good automation is not about removing the human from the process. It is about automating repetitive work while keeping important decisions visible and controllable.` },
    ],
    highlights: ["Internship discovery","CV based matching","Recruiter research","Personalized emails and cover letters","Application tracking","Follow up tracking","Human review of automated steps","One unified application workflow"],
    stack: ["Full stack web","Workflow automation","LLM integration","AI assisted writing"],
  },
  {
    slug: 'ai-investment-platform',
    doorNumber: '08',
    order: 8,
    complexity: 4,
    category: 'fullstack',
    doorKind: 'vault',
    title: 'AI Investment Platform',
    type: 'Financial research platform · Personal project',
    tagline: `An AI powered investment research platform that combines market research, company analysis, portfolio tracking and specialized agents in a single interface.`,
    preview: `Specialized AI agents for market research, company analysis, portfolio monitoring and investment Q&A, feeding one dashboard where sourced data stays separate from generated analysis.`,
    previewStack: 'Multi agent AI · Full stack · Dashboard',
    status: 'Public',
    links: [{ label: 'Repository ↗', href: 'https://github.com/AraGhah/CapitalOS', primary: true }],
    meta: [['Role', 'Full stack development and AI architecture'], ['Team', 'Individual'], ['Year', '2026'], ['Status', 'Public']],
    whyRated: `A multi agent architecture with distinct responsibilities, market and portfolio data feeding one dashboard, and a hard line between sourced information and generated analysis, in a domain where outdated data changes the conclusion.`,
    sections: [
      { heading: 'The brief', body: `The AI Investment Platform is designed to organize the large amount of information involved in researching investments. Specialized AI agents analyze companies, financial news and market data while the platform provides a central place to track and examine a portfolio.` },
      { heading: 'What had to hold', body: `Financial information had to remain traceable and separated from generated analysis. The system needed to help users understand why information mattered instead of simply producing unsupported investment conclusions.` },
      { heading: 'How I built it', body: `I designed the platform around multiple specialized AI agents with distinct responsibilities, including market research, company analysis, portfolio monitoring and investment Q&A. These systems are connected through a unified dashboard.` },
      { heading: 'My slice of it', body: `I designed the multi agent architecture and the main product workflow, including how research, portfolio data, market information and AI generated analysis are organized and presented to the user.` },
      { heading: 'Where the risk was', body: `The largest risk was treating AI generated analysis as fact. Financial information changes quickly, and incorrect or outdated information can completely change the interpretation of an investment.` },
      { heading: 'The lesson', body: `An investment tool becomes more useful when it explains the evidence behind an analysis. This project pushed me to design AI systems around traceability, specialized responsibilities and user verification rather than a single black box answer.` },
    ],
    highlights: ["Multi agent architecture","Market research agent","Company analysis agent","Portfolio monitoring","Investment Q&A","Financial news analysis","Sourced data kept separate from generated analysis","Unified research dashboard"],
    stack: ["Full stack web","Multi agent AI","LLM integration","Financial data","Dashboard design"],
  },
  {
    slug: 'urban-crisis-protocol',
    doorNumber: '09',
    order: 9,
    complexity: 5,
    category: 'software',
    doorKind: 'blueprint',
    title: 'Urban Crisis Protocol',
    type: 'AI simulation game · Academic team project',
    tagline: `A real-life simulation game where a human player competes against an AI to develop, manage and protect a town under changing conditions.`,
    preview: `Two towns, one run by the player and one run entirely by an AI, compete under the same conditions while tornadoes, power outages and bandit attacks interrupt both. My part was the crisis events that keep either side from progressing too easily.`,
    previewStack: 'C# · Unity · AI decision-making',
    status: 'Public',
    links: [],
    meta: [['Role', 'Gameplay systems and events'], ['Team', 'Collaborative'], ['Year', '2026'], ['Status', 'Public']],
    whyRated: `Two towns simulated side by side, one of them driven by an AI that makes its own decisions, with crises that cascade through resources, infrastructure and large-scale destruction on both sides while keeping the competition fair, built by a team. Scored on design and scope, not on whether it shipped.`,
    sections: [
      { heading: 'The brief', body: `Urban Crisis Protocol is a simulation game built with Unity and C# where two towns compete against each other. One town is managed by the player, while the second is entirely controlled by an AI. The goal is to observe how the AI develops its town, manages resources, reacts to crises and adapts its strategy in order to outperform the human player.` },
      { heading: 'What had to hold', body: `Both towns needed to operate under comparable conditions so that the competition remained meaningful. The AI had to make its own decisions while reacting to the same types of problems and opportunities as the player.` },
      { heading: 'How we built it', body: `Our team developed the simulation in Unity using C#. The project combines town management, resource systems, AI decision-making and disruptive events such as tornadoes, power outages, bandit attacks and large-scale destruction.` },
      { heading: 'My slice of it', body: `My focus was on making the competition more difficult and unpredictable. I worked on crisis events that interrupt development, force both the player and the AI to adapt and prevent either town from progressing too easily.` },
      { heading: 'Where the risk was', body: `The main challenge was creating events that could affect both sides without making the simulation unfair. The AI also needed to react logically to unexpected situations instead of following a completely fixed strategy.` },
      { heading: 'The lesson', body: `Building a human-versus-AI simulation taught me that AI behaviour becomes much more interesting when it has to react to uncertainty. The goal is not simply to make the AI stronger, but to observe how its decisions change when the environment becomes unpredictable.` },
    ],
    highlights: ["Human versus AI competition","AI-controlled rival town","Town and resource management","Event driven crisis systems","Tornado and power outage events","Bandit attack events","Large-scale destruction","Team based development"],
    stack: ["C#","Unity","AI decision-making","Event driven systems","Gameplay systems"],
  },
  {
    slug: 'sentinelops',
    doorNumber: '10',
    order: 10,
    complexity: 5,
    category: 'software',
    doorKind: 'secure',
    title: 'SentinelOps',
    type: 'Cloud native security and incident management platform',
    tagline: `A platform for collecting, analyzing and managing security events, giving analysts one place to review alerts, prioritize incidents and coordinate a response.`,
    preview: `Security events arrive from many systems in many formats. SentinelOps normalises them into one model and moves them through a structured incident workflow, so analysts work a ranked queue instead of a firehose.`,
    previewStack: 'AWS · ASP.NET Core · Incident response',
    status: 'Public',
    statusNote: `SentinelOps is an evolving portfolio project. Future phases include deeper AWS integrations, automated enrichment, notification workflows, infrastructure automation and advanced security analytics.`,
    links: [],
    meta: [['Role', 'Architecture and full stack'], ['Year', '2026'], ['Domain', 'Security operations'], ['Status', 'Public']],
    whyRated: `Cloud event ingestion, a normalized security event schema, structured incident workflow, authenticated API, relational persistence, logging and failure handling, in a domain where a bug has real consequences. Scored on architecture and risk, not hours spent.`,
    sections: [
      { heading: 'The premise', body: `SentinelOps is a cloud native platform for collecting, analyzing and managing security events. It gives security teams a centralized interface for reviewing alerts, prioritizing incidents, tracking investigations and coordinating responses.` },
      { heading: 'The noise problem', body: `Security events originate from many systems and arrive in different formats. Without normalization and prioritization, teams struggle to identify the threats that matter, understand their context and respond consistently.` },
      { heading: 'The system', body: `SentinelOps transforms incoming events into a standardized security event model and moves them through a structured incident management workflow. The platform connects cloud event processing to a backend API, persistent storage and a responsive analyst dashboard.` },
      { heading: 'My end of it', body: `I designed the platform architecture, security event schema, backend structure, cloud processing workflow and frontend experience. I focused on drawing clear boundaries between event ingestion, validation, storage, analysis and incident response.` },
      { heading: 'The hard constraint', body: `Designing a system that processes events reliably while keeping full traceability. Every event has to be validated, normalized and connected to an incident without losing the information an analyst needs to investigate it.` },
      { heading: 'The perspective shift', body: `Security tooling fails quietly if you let it. The habit I took from this project is designing for the analyst who is tired at 3am: fewer alerts, but every one traceable back to the raw event that caused it.` },
    ],
    highlights: ["Standardized security event schema","Cloud based event ingestion and processing","Incident creation, prioritization and status tracking","Structured backend API","Analyst facing React dashboard","PostgreSQL persistence","Authentication, validation and standardized responses","Logging, error handling and API documentation","Infrastructure designed for scale and future automation"],
    stack: ["AWS","ASP.NET Core","C#","React","PostgreSQL","REST APIs"],
  },
];

export function getProjectEn(slug: string) {
  return projectsEn.find((p) => p.slug === slug);
}
